### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by Slashek** [Platform-OS/platformos-documentation#1278]
Currently, the only way to handle asynchronous tasks is to constantly poll the server. We would like to be able to use WebSockets to enhance the user experience.

**Comment by mattwalter91** [comment]
I think that in a lot of cases webhooks would work. That's what you use for instance_create, and it would works for processes like imports. We just need to know when the process is complete, and there's no real back and forth between us.

Not sure if that's easier since you have it in other places. There might be cases for websockets that I'm not thinking of too.

**Comment by richxrich** [comment]
Websockets are good for persistent connections where things need to be real time, mobile apps, etc... also can be used for real time video and audio if you want to explore array buffers :)

**Comment by mattwalter91** [comment]
I read "constantly poll the server" and thought of where we do that, which is checking site copy status and import status. In that situation a webhook returning the single result would be the better option I think.

I understand what you mean though. Is this task is for custom use, like receiving updates on model data?

**Comment by onecreative** [comment]
@mattwalter91 I think webhooks should be a separate request. Both features are needed.

**Comment by richxrich** [comment]
@mattwalter91 Push notifications are essentially socket connections, they are an always connected state to Apple or Google who then push something to the phone when needed. I used to work in finance and all our IoT devices or hardware terminals were connected via sockets in order to have faster processing, real time feedback, and the fact the end device could be behind unknown levels of networking. Basically if you got a connection there was nothing else to worry about. 

Clickup and Google sheets etc all use websockets for the speed and realtime interaction with multi users....

**Comment by Slashek** [comment]
The new version of the https://getmarketplace.co/ (code available here https://github.com/mdyd-dev/product-marketplace-template) will include chat built using WebSockets - coming next week! Behind the scenes, we will continue working on backend stuff. This is still highly experimental, however should give you a taste of what to expect. For now, backend logic can be handled by partials with the `channels/` prefix (for example https://github.com/mdyd-dev/product-marketplace-template/blob/master/modules/chat/public/views/partials/channels/conversate.html.liquid ), but it might be a good idea to extract it to a separate folder, like `app/channels/` instead of relying on the convention. Looking for your feedback!
