### ISSUE TITLE
Move content from Docs to Community site

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#1361]
Move release notes to community site.

Alongside Town Hall archive.

It should be much better place to spread the love around docs.

@diana-lakatos Im creating card here even though its a big task spanning across at least 3 projects, but first step will probably involve moving RN page from Docs to community site and you should know about it all :)

ETA: Unknown yet, probably after groups are done within our community site - one of the groups will be "News" or "Announcements" and it will group all our communication about features, etc. Same for town hall.

**Comment by diana-lakatos** [comment]
@pavelloz 
I think moving the Town Hall archive to the community site is a great idea! 

We discussed  moving the release notes with @Nagygyorgy and also looked for some examples, and many of the companies have the release notes on the documentation site so that might be where users look for them, for example:

- Sendgrid: https://sendgrid.com/docs/release-notes/
- Twilio: https://www.twilio.com/docs/flex/release-notes
- Ant: https://ant.design/changelog
- mapbox: https://docs.mapbox.com/api/changelog/
- Heroku: https://devcenter.heroku.com/changelog

Firebase has it under Support: https://firebase.google.com/support/releases

Why do you think we should move the release notes?  Did you see some examples of release notes on community sites? 

Another idea: We could move the status reports to the community site, those always have links to the release notes. What do you think? 

Thanks!

**Comment by pavelloz** [comment]
Well, for one, our release notes have more info tha just tech stuff (which docs are for and used by other companies above) - we announce blog posts, etc.
Second - on community site there is room for discussion
Third - having it in community will allow us to centralize notifications - people will join group and get notifications (in app, email) when something new appears - and this might be in between weeks, and not release note at all

**Comment by diana-lakatos** [comment]
> Well, for one, our release notes have more info tha just tech stuff (which docs are for and used by other companies above) - we announce blog posts, etc.

Do you mean the status reports? E.g. https://www.platformos.com/blog/post/platformos-status-report-jan-25-2021 
I don't think our release notes have article announcements. If you mean the status reports, I agree they should be on the community site and it's good to provide room for discussion because partners often start a discussion about them on Slack. 

About the notifications, I think they could be separate from release notes. The release note before or after the notification could of course include the notification depending on the topic.

**Comment by pavelloz** [comment]
Yes, i mean status reports.

SR -> Notification @ email/community site -> Visitor comes in -> Links to docs/details 

Notification is always after the action it notifies about ;)

**Comment by diana-lakatos** [comment]
Then we are totally on the same page, yes, status reports should be on the community site. 
I am the one who usually uploads them, so let's please discuss the format when we arrive at that stage.

With "before", I meant the announcement of something like a scheduled maintenance but you're right we don't call that a notification.

**Comment by diana-lakatos** [comment]
As no content will be moved from the documentation site, this issue has been added to the Community site Issue queue.
https://github.com/Platform-OS/pos-community/issues/97
