### ISSUE TITLE
Support questions

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1362]
We collect support questions that our documentation should answer/provide further reading on in this ticket. We will later either create a FAQ page or put the answers in the respective topics. 

- [x] How to handle HTML 5 routing (Browser history API)?
- [x] How to define new graphql types definitions?
- [ ] Can we use Form validations in REST API endpoint?
- [x] Authorization Policy failure does not interrupt execution of page logic(It just sets request response status to 403), is it intent behavior of authorization policy or some kind of bug in code(I followed documentation to create sample authorization_policy and test page)?
- [x] Handle authorization policy failure while using page as REST API endpoint(Like returning json response without redirect)?
- [x] How to achieve transactional query operations?
- [x] How to define indexes in model schema?

**Comment by pavelloz** [comment]
>  How to handle HTML 5 routing (Browser history API)?

https://developer.mozilla.org/en-US/docs/Web/API/History_API

>  How to define new graphql types definitions?

You cant. You can create properties in models in various types, the list of types in graphql is hardcoded.

>  Authorization Policy failure does not interrupt execution of page logic(It just sets request response status to 403), is it intent behavior of authorization policy or some kind of bug in code(I followed documentation to create sample authorization_policy and test page)?

To break logic flow use `break` tag (the same that is used for breaking out of for loop). Example usage in next question.

>  Handle authorization policy failure while using page as REST API endpoint(Like returning json response without redirect)?

Using partial is better in that case. For example:

#### app/views/partials/lib/present_or_404.liquid
 
```
{% liquid
  unless property
    render 'theme/simple/404', status: 404
    break
  endunless
%}
```

^ It will do/render what you want, and break the flow (return to server at this point)

Usage:
```
...
{%  include 'lib/present_or_404', property:  comment.id %}
...
```

>  How to achieve transactional query operations?

Every mutation is transactional because it has consequences in the database, query has no consequences so its not transactional.

>  How to define indexes in model schema?

You cant.
