### ISSUE TITLE
marketplace-kit npm install update

### ISSUE THREAD

**Issue by digitalfuel** [Platform-OS/platformos-documentation#195]
https://documentation.platform-os.com/get-started/setup/updating-marketplace-kit

#### Updating marketplace-kit

npm -g install @platform-os/marketplace-kit => npm i -g @platform-os/marketplace-kit

sudo npm i -g @platform-os/marketplace-kit

Not sure this is wrong but is inconsistent. If sudo npm i -g @platform-os/marketplace-kit works to install and update why use npm -g install @platform-os/marketplace-kit for update. Simpler if they are all the same.

**Comment by pavelloz** [comment]
From what i remember it does something different (sudo vs none), when it comes to location of installed package, when you have local and global nodejs installed.

Usually sudo isnt needed, but sometimes it is.

**Comment by digitalfuel** [comment]
Sorry did not explain this very well. Yes Sudo is different. It works on mac for global permissions I think. I was just showing it uses "npm i -g"

It was more meaning the use of **"npm -g install"** vs **"npm i -g"**. In the updating marketplace-kit doc it uses "-g install" when all the rest of the docs and git use "i -g" for both install and update. So in the updating marketplace-kit
**npm -g install @platform-os/marketplace-kit**  would become  **npm i -g @platform-os/marketplace-kit** for consistency and simplicity.

**Comment by pavelloz** [comment]
Ouh right.

Im pretty sure that i just changed my mind in the process and decided to use `i` instead of `install`, but maybe i should ask for second opinion:

Is it better to use abbreviation in this case? In most projects documentation says the full `install` command name - I personally only use the shortcut when i work with npm but its less known (and less explicit) than the full `install` version.

Examples of other projects:

* https://github.com/eslint/eslint#global-installation-and-usage 
* https://prettier.io/docs/en/install.html 
* https://github.com/graphql/graphiql#getting-started

What do you think?

**Comment by pavelloz** [comment]
I think i just answered my own question - ill fix the problem ;)

**Comment by pavelloz** [comment]
Hopefully this helps:

https://github.com/mdyd-dev/nearme-documentation/commit/431150eec428babb33d98f2bd608930601c15375

https://github.com/mdyd-dev/marketplace-kit/commit/eda17fa42880fd1982a6ac4fa6966cc80d38a598
