### ISSUE TITLE
Reorganize examples

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#339]
Reorganize examples to be easy to use for beginners. Ideas so far:

Instead of putting all examples in nearme-example it would be much better to create new github repository platform-os-examples, and put every example separately on new public repo with simple commands to install:
1. Create instance in PP
2. Clone repository
3. Deploy and enjoy

**Comment by pavelloz** [comment]
Whats wrong with having all examples in one repo that can be cloned, deployed and enjoyed? ;)

We try to keep files separated/grouped into directories that are titles somewhat accordingly to the example, so they are easily accessible. Its easier to have it in one place, because some examples depend on others, ie. need account to reset password, etc.

**Comment by diana-lakatos** [comment]
Our current approach for examples works, especially with the index now in place.
