### ISSUE TITLE
Write tutorial for uploading the CBO free Dashboard

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#342]
detailed step by step instructions on how to upload the CBO free Dashboard

**Comment by pavelloz** [comment]
This might be better left for CBO team to handle, otherwise we will need to have our finger release cycle and update on any changes etc.

Plus, this is not really platform thing - if it needs some special deployment process, then we shouldn't get involved, otherwise one day we might find ourselves debugging someones inability to deploy someone else's code that we don't know/support/can fix.
