### ISSUE TITLE
Describe our development  and deployment process

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#477]
- development
- QA
- Staging
- CI
- CD
- Production

**Comment by piotrze** [comment]
@diana-lakatos Why we want this? It is our internal process for developing product. Our product is build with different tools than clients will use to build their instances. 

If we want to teach them how to have good process we need to show them example that is based on creating product that is build on top of our platform. Otherwise there are too many differences.

**Comment by diana-lakatos** [comment]
@piotrze This would be a topic for the Best Practices section that would help our Partners build their development workflow using the experiences and insights we share. Of course, we should only include information that is useful to them, like using version control, how to use testing-staging-production sites, testing, QA, recommended tools, etc. 

I can write a draft based on information I already have, and then I'd ask you to review, edit, and extend.

**Comment by pavelloz** [comment]
Yeah, describing how we develop and deploy the platform doesnt make sense, nobody will ever use it and probably we dont even want to share it for many reasons.

We should focus on how we develop and deploy a project onto platform.
