### ISSUE TITLE
Describe background tag

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#489]
https://github.com/mdyd-dev/desksnearme/issues/7677

**Comment by pavelloz** [comment]
Hmmm. This tag will have automatically generated documentation, so i guess this article should be an explanation when/how to use it and why + examples.

**Comment by pavelloz** [comment]
This will be autogenerated (pretty good imo, Slashek ):


---

## background_tag

Invokes code within the tag in the asynchronously, in the background.

### Arguments:

- **options** [Hash]: Any variable provided to the background tag will become accessible in the code. There is one special key, "delay" [Integer], which defines
  number of minutes to delay running code (defaults to 0, which means run code as soon as possible)
You will have access only to variables you explicitly pass to the background tag. The context object is available by default, however with limitations - you would need
to explicitly pass page/layout metadata if you wanted to use it, as well as device and constants.

### Examples:

The following code will run all the log queries in the background, not earlier than 5 minutes since the execution. You will have access only to variables
explicitly provided to the background tag, which are "data" and "hey" variable. Note that you will not have access to "my_data" variable. Also note
that the result of this background tag will not be rendered, and you will not have access to any variable inside the background tag.

    {% parse_json my_data %}{ "hello": "world" }{% endparse_json %}
    {% assign not_available_in_background = "You will not see me" %}
    {% background delay: 5, data: my_data, hey: 'hello' %}
      {% log not_available_in_background %}{% comment %}Will be null, as this variable was not passed to the background tag {% endcomment %}
      {% log data %}{% comment %}You will see { "hello": "world" }, as it was provided to the background tag{% endcomment %}
      {% log hey %}{% comment %}You will see "hello" as it was provided to the background tag{% endcomment %}
      {% log context %}{% comment %}We will copy the current request context and make it available in the background{% endcomment %}
      {% assign not_available_outside = "You will not see me" %}
      {{ not_available_outside }} {% comment %}This variable will be rendered in the background, meaning you won't see anything on the page{% endcomment %}
    {% endbackground %}
    {{ not_available_outside }}{% comment %}This will be blank, because the assign will happen in the background - you won't have access to it here{% endcomment %}

**Comment by pavelloz** [comment]
@Slashek is it up to date? The context part especially

**Comment by diana-lakatos** [comment]
@pavelloz @Slashek We would also need some information on what the benefits are, as background jobs are mentioned in pricing (<-this might be in the separate topic that Pawel suggested).

**Comment by pavelloz** [comment]
Heres the most up to date documentation on background tag: 
https://documentation-staging.staging.oregon.platform-os.com/api-reference/liquid/platformos-tags#background

Soon on production

**Comment by diana-lakatos** [comment]
https://documentation.platform-os.com/api-reference/liquid/platformos-tags#background
