### ISSUE TITLE
Make a page with most negative/positive feedback pages 

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#517]
To have some kind of overview.
This will require authorization.

cc @diana-lakatos

**Comment by diana-lakatos** [comment]
Currently, this information is collected in a file. It would be very helpful to have a list of all pages and positive, neutral, and negative feedback in a table view (or something similar). So I'd be very happy to have an overview of all pages, not only the ones with the most positive/negative feedback.

**Comment by pavelloz** [comment]
Ok, ill define "the most" in a relaxed way (ie. has any feedback ;) )

**Comment by Developer-DNM** [comment]
@pawel a customisation could collect all this, and later we can add an Admin with some simple reporting and filtering to see how things trend.

Maciek has a way to collect anonymous user (non registered) form submissions

**Comment by pavelloz** [comment]
Customization is collecting all this already ;)
After some time, we have some data, so can try and analyze it

**Comment by diana-lakatos** [comment]
For displaying the feedback information in a meaningful way, we also need to be able to filter for a time period. For example, the How platformOS Works section got negative feedback in the beginning, but then since we updated it, it gets a lot of positives. So if we just summarize the results, it looks as if some users were satisfied while others weren't satisfied with the same content but that's not the case.

**Comment by diana-lakatos** [comment]
Closing this, we are keeping track of feedback manually for now. Will open new ticket when needed.
