### ISSUE TITLE
Tutorial: Resetting password without user profiles

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#527]
Feedback on: 
https://documentation.platform-os.com/tutorials/users/resetting-password-authenticated-user

Feedback:
I'd like to see this without the use of user_profiles.

**Comment by onecreative** [comment]
This may not be worthwhile for now, since we will need a few enhancements to the platform before an alternative method is any better than what we currently have using user_profiles.

Specifically, we will need:
-  the ability to submit a form without a resource. The form data would simply be used to populate data for the email notification.
- Possibly a change to the way tokens are created and stored. Currently they are created via a query, and the token changes each time it is queried. This behavior, though intended, is strange and unexpected.

**Comment by Slashek** [comment]
one can use for example `email_send` graphql mutation
