### ISSUE TITLE
Liquid tags: format parameter description

### ISSUE THREAD

**Issue by piotrze** [Platform-OS/platformos-documentation#705]
![image](https://user-images.githubusercontent.com/96238/65146174-78f7f900-da1b-11e9-9510-9b709da0395a.png)
![image](https://user-images.githubusercontent.com/96238/65146208-9200aa00-da1b-11e9-8241-03f33817389b.png)

**Comment by pavelloz** [comment]
Improvement so far:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/546845/72012896-0fffef80-325d-11ea-972d-5bb92fb011aa.png">

Since this is one long string, without backend intervention i think we need to stay at that. Maybe bolding name of key would help (delay, priority, etc)

**Comment by pavelloz** [comment]
Phase 2:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/546845/72066803-cb6a6780-32e1-11ea-9d5c-0235f1e1219c.png">
