### ISSUE TITLE
Update code example in Resetting Password of an Authenticated User topic

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#788]
User feedback:

Please note that the example code for "Resetting Password of an Authenticated User", does not work. In Step 2, the following line must be modified as follows:
`resource: reset_password`
change to
`resource:  modules/users/reset_password`

https://documentation.platformos.com/tutorials/users/resetting-password-authenticated-user

**Comment by pavelloz** [comment]
Hmm, this might need some more love.

Doc was written before module feature, and whoever reported it, took code from `examples` repo which is using modules. Both are correct in isolation.

Doc is now incorrect, because it assumes being in a module called `users`, but its not, according to tutorial text.

Examples page is correct, but its never linked from this tutorial, so its mixing two things really.

**Comment by diana-lakatos** [comment]
To do:

1. Change example back to how it works without modules, and add a note about adjusting path if you're using modules. 
2. Verify if this tutorial is compatible with the module we have in examples and link to it + update paths to reflect that. (I will create a separate ticket for this task.)
