### ISSUE TITLE
Expand gui serve document

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#942]
How to use:
* docs
* explorer
* variables
* prettifier
* multiple queries
* directives
* default values

https://documentation.platformos.com/best-practices/qa/developing-graphql-queries-using-pos-cli-gui

**Comment by pavelloz** [comment]
BTW this article doesnt fit Best practices -> QA

Its probably more for developer guide or best practices -> Developing

Something new, where we could keep advice how to develop code effectively, just like we did with Best practices -> Performance

**Comment by diana-lakatos** [comment]
@pavelloz We are planning a whole category for GraphQL (Developer Guide/GraphQL), could it go there?

**Comment by pavelloz** [comment]
Yes, i think that would be a good place. Put there everything that explains how to use GQL in pOS effectively.

**Comment by pavelloz** [comment]
But wait till im done with GraphiQL article :)

**Comment by diana-lakatos** [comment]
@pavelloz OK, looking forward to it.

**Comment by diana-lakatos** [comment]
@pavelloz What do you think about renaming the INTRODUCTION category in the Developer Guide to DEVELOPMENT, and putting the GraphQL-related topics there? Something like this:

Instead of: 

![Screenshot 2020-03-13 at 6 28 07](https://user-images.githubusercontent.com/4191691/76592489-d31dd680-64f3-11ea-87b4-cfa200ee456f.jpg)

It would be:

DEVELOPMENT
About platformOS
Development Workflow
pos-cli
Codebase
GraphQL (includes Developing GraphQL Queries Using pos-cli gui and later topics related to GraphQL) 
Technologies
Glossary

So I would show the subtopics of platformOS Workflow immediately, and this would give a nice overview of everything one needs to develop on platformOS.

**Comment by pavelloz** [comment]
Yes, this makes sense.

Even though this one article on graphiql is more like "get started" / "introduction", graphql is such a big (and important) part of working with the platform, grouping advice/best practice in the future will for sure be beneficial to a lot of people.

**Comment by diana-lakatos** [comment]
https://documentation.platformos.com/developer-guide/graphql/developing-graphql-queries-using-graphiql
